version: "3.8"
services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: moonshot
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  backend:
    build: .
    depends_on:
      - db
    environment:
      - NODE_ENV=production
    # ports:
    #   - "4000:4000"
    deploy:
      replicas: 1
    restart: always

volumes:
  pgdata:
